### ISSUE TITLE
UI Core 5.0

### ISSUE THREAD

**Issue by flaviendelangle** [habx/lib-design-system#1528]
### Changes

See `theme.interface.ts` comments for more details

- `theme.textColor` no longer accept an `opacity` config **BREAKING**
- `theme.textColor` new config key `variationPropName` to choose dynamically the variation to apply
- `theme.color` config key `propName` has been renamed `valuePropName` **BREAKING**
- `theme.color` new config key `variation` to choose among a set of pre-determined text colors

- `theme.color` config key `propName` has been renamed `valuePropName` **BREAKING**

- `theme.font` config has been removed (we have a single font in the theme now) **BREAKING**

- `theme.neutralColor` : new method to replace direct calls to `palette.darkBlue` and prepare local and global dark modes

#### ThemeProvider

- `backgroundColor` prop has been removed, use `BackgroundThemeProvider` **BREAKING**

#### Button

- `large` prop has been removed **BREAKING** (`large` buttons can be replaced by default sized buttons)
- `warning` prop has been removed **BREAKING** (should be replaced with `error`)
- new prop `ghost` for a Button without background / border but with a regular dimensions (as opposed to link button)

#### Text
- `opacity` prop has been removed **BREAKING**
  - `<Text opacity={1} />` => `<Text variation="title" />`
- new prop `variation` to choose among a set of pre-determined text colors

#### Title
- `opacity` prop has been removed **BREAKING**

#### NavBar

- `backgroundColor` prop is now required **BREAKING**
- `color` prop has been removed **BREAKING**

#### Replace direct `palette` calls

In CSS :

```ts
// v4
const MyComponent = styled.div`
  border: 1px solid ${palette.darkBlue[200]}`
`

// v5
const MyComponent = styled.div`
  border: 1px solid ${theme.neutralColor(200)}`
`
```

In JS :

```tsx
// v4
const MyComponent: React.FC = () => {
  return <Background color={palette.darkBlue[300]} />
}

// v5
const MyComponent: React.FC = () => {
  const theme = useThemeVariant()

  return <Background color={theme.neutralColor.withIntensityFading[200]} />
}
```

#### Use new `ActionBar` guidelines

Use `ghost` buttons instead of `link` buttons for 2nd and 3rd button

```tsx
// v4
<ActionBar>
  <Button link>Annuler</Button>
  <Button warning>Confirmer</Button>
</ActionBar>

// v5
<ActionBar>
  <Button ghost>Annuler</Button>
  <Button error>Confirmer</Button>
</ActionBar>
```

**Comment by flaviendelangle** [comment]
### Habx Library migration

#### Breaking changes

- `config-ci-front` : https://github.com/habx/config-ci-front/pull/16 => Released
- `lib-client-documents` : https://github.com/habx/lib-client-documents/pull/377 => Released
- `lib-client-housing-2d` : https://github.com/habx/lib-client-housing-2d/pull/1477 => Released
- `ui-table` : https://github.com/habx/ui-table/pull/705 => Released
- `lib-client-orbital` : https://github.com/habx/lib-client-orbital/pull/563 => Released
- `lib-client-finishes` : https://github.com/habx/lib-client-finishes/pull/68 => Released
- `lib-client-map` : https://github.com/habx/lib-client-map/pull/586 => Released
- `lib-client-tracking` : https://github.com/habx/lib-client-tracking/pull/343 => Released
- `lib-client-cloudinary-input` : https://github.com/habx/lib-client-cloudinary-input/pull/423 => Released
- `lib-client-notifications` : https://github.com/habx/lib-client-notifications/pull/95 => Released


#### No breaking changes:

- `lib-client-reporting` => Released
- `lib-client-pano` => Released
- `lib-form-helper` => Released
- `lib-client-acl` => Released
- `lib-client-involvements` => Waiting for dep
- `lib-client-housings` => Waiting for dep

**Comment by jean9696** [comment]
Noticed Bugs:
* icon aligment in basic `Button`
![Capture d’écran 2020-12-02 à 10 11 42](https://user-images.githubusercontent.com/13215843/100852729-2e7b6480-3487-11eb-817b-e3375188135e.png)

**Comment by alexisfontaine** [comment]
On Firefox `83` (borders are visible in the corners):
![image](https://user-images.githubusercontent.com/9002807/100863756-507be380-3495-11eb-9737-d9d9969910b7.png)
